config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, :path => '/admin', :path_names => { :sign_in => "login" }

  resources :blogs
  resources :projects
  resources :about

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, uniqueness: true, presence: true
    validates :content, presence: true
    validates :on_card, presence: true

    has_one_attached :img
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @pagy, @blogs  = pagy(Blog.order(id: :asc), items: params[:per_page])
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :content, :on_card, :img)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= blog.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Content:</strong>
    <%= blog.content %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">On card:</strong>
    <%= blog.on_card %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this blog", blog, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this blog', edit_blog_path(blog), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, class: "contents") do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label "Cover Image" , class: "primary-text-color" %> <br/>
    <%= form.file_field :img, accept: "image/*", required: action_name == "new" , class: "mt-3 block text-sm text-gray-500
      file:mr-4 file:py-2 file:px-4
      file:rounded-md file:border-0
      file:text-sm file:font-semibold
      file:bg-main file:text-white
      file:cursor-pointer" 
    %>
  </div>

  <div class="my-5">
    <%= form.label :content %>
    <%= form.text_area :content, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :on_card %>
    <%= form.text_area :on_card, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<main class="flex-1 container my-4">
  <h1 class="font-bold text-4xl">Editing blog</h1>

  <%= render "form", blog: @blog %>

  <%= link_to "Show this blog", @blog, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to blogs", blogs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</main>

app/views/blogs/index.html+turbo_frame.erb
<%= turbo_frame_tag "page_handler" do %>

<% end %>

app/views/blogs/index.html.erb
<main class="flex-1">
  <%= page_header_component title: "Latest stories and articles", 
    highlight: "Thoughts on work, life, and the universe, but mostly just programming",
    bgColor: ""
  %>
  <% if user_signed_in? %>
    <div class="container mt-6 -mb-6">
      <%= button_component type: "create", link: new_blog_path(@blog), text: "Create new blog", additionalClass: "mb-8" %>
    </div>
  <% end %>
  <%= turbo_frame_tag "page_handler" %>
  <div id="blogs" class="bg-gray-100 dark:bg-gray-700 transition-colors duration-200 py-12">
    <div class="container grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-10">
      <% @blogs.each do | blog| %>
        <%= blog_card_component blog: blog %>
      <% end %>
    </div>
  </div>
</main>

app/views/blogs/new.html.erb
<main class="flex-1 container my-4">
  <h1 class="font-bold text-4xl">New blog</h1>

  <%= render "form", blog: @blog %>

  <%= link_to 'Back to blogs', blogs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</main>

app/views/blogs/show.html.erb
<main class="flex-1 container my-4">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @blog %>

    <%= link_to 'Edit this blog', edit_blog_path(@blog), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this blog', blog_path(@blog), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to blogs', blogs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</main>