config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, :path => '/admin', :path_names => { :sign_in => "login" }

  resources :blogs
  resources :projects
  resources :about

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/project.rb
class Project < ApplicationRecord
    validates :title, uniqueness: true, presence: true
    validates :content, presence: true
    validates :project_start, presence: true
    validates :on_card, presence: true

    has_one_attached :img
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, only: %i[ new create edit update destroy ]
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @pagy, @projects = pagy(Project.order(id: :asc), items: params[:per_page])
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :content, :project_start, :project_end, :img, :on_card)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js", "data-turbo-track": "reload"  %>
<%= stylesheet_link_tag "monokai", "data-turbo-track": "reload" %>
<%= javascript_include_tag "quill", "data-turbo-track": "reload"  %>
<%= stylesheet_link_tag "quill/dist/quill.snow.css", "data-turbo-track": "reload" %>
<%= javascript_include_tag "quill-image-resize-module", "data-turbo-track": "reload"  %>

<%= form_with(model: project, class: "contents") do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title, class: "primary-text-color" %>
    <%= form.text_field :title, required: true, placeholder: "Write a title..", class: "block dark:bg-dark dark:text-white rounded-md border border-[#ccc] outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :on_card, class: "primary-text-color" %>
    <%= form.text_area :on_card, rows: 3, required: true, placeholder: "Write card details..", class: "block dark:bg-dark dark:text-white rounded-md border border-[#ccc] outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label "Cover Image" , class: "primary-text-color" %> <br/>
    <%= form.file_field :img, accept: "image/*", required: action_name == "new" , class: "mt-3 block text-sm text-gray-500
      file:mr-4 file:py-2 file:px-4
      file:rounded-md file:border-0
      file:text-sm file:font-semibold
      file:bg-main file:text-white
      file:cursor-pointer" 
    %>
  </div>

  <div class="my-5 grid grid-cols-1 md:grid-cols-4 gap-3">
    <div>
      <%= form.label :project_start, class: "primary-text-color" %>
      <%= form.date_field :project_start, max: Date.today, required: true, class: "block dark:bg-dark dark:text-white rounded-md border border-[#ccc] outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    <div>
      <%= form.label :project_end, class: "primary-text-color" %>
      <%= form.date_field :project_end, max: Date.today, class: "block dark:bg-dark dark:text-white rounded-md border border-[#ccc] outline-none px-3 py-2 mt-2 w-full" %>
    </div>
  </div>

  <div class="my-5" data-controller="quilleditor" >
    <%= form.label :content, class: "primary-text-color" %>
    <%= form.hidden_field :content, data: { "quilleditor-target": "input" } %>
    <div class="mt-2">
      <div class="min-h-[500px]" data-quilleditor-target="editor"></div>
    </div>
  </div>
 
  <div class="inline">
    <%= form.submit class: "rounded-lg py-2 px-5 bg-main text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/projects/_pager.html.erb
<% if pagy.next %>
    <div id="pager" data-controller="pager" class="my-8 flex justify-center">
        <%= link_to(
            "Load more..",
            projects_path(page: pagy.next),
            class: "text-sm text-white hover:scale-105 hover:shadow-md py-2 px-5 bg-main font-medium",
            data: { turbo_frame: "page_handler", action: "click->pager#loading", pager_target: "btn"}
        ) %>
    </div>
<% end %>

app/views/projects/_project.html.erb
<div class="primary-text-color" id="<%= dom_id project %>">
  <div class="relative flex items-center justify-center w-full h-40 lg:h-56">
    <div class="absolute w-full h-full bg-black opacity-40"></div>
    <h1 class="absolute mx-5 md:mx-10 text-white text-center text-2xl md:text-3xl lg:text-[3rem] leading-7 lg:leading-[3rem] font-normal"><%= project.title %></h1>
    <img class="w-full h-full object-cover object-center" src="<%= rails_blob_url(project.img) %>" loading="lazy">
  </div>

  <p class="my-5">
    <span class="text-xl">"</span><%= project.on_card %><span class="text-xl">"</span>
  </p>

  <div data-controller="quillreadonly" >
    <%= project.content.html_safe %>
  </div>

  <p class="my-5">
    <strong class="block font-medium mb-1">Project start:</strong>
    <%= project.project_start.strftime("%B %Y") %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Project end:</strong>
    <%= project.project_end.strftime("%B %Y") rescue "present" %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this project", project, class: "rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    <%= link_to 'Edit this project', edit_project_path(project), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 font-medium" %>
  <% end %>
</div>

app/views/projects/edit.html.erb
<main class="flex-1 container my-4">
  <h1 class="font-medium primary-text-color text-3xl">Editing project</h1>

  <%= render "form", project: @project %>

  <%= link_to "Show this project", @project, class: "ml-2 rounded-lg py-2 px-5 bg-gray-100 dark:bg-dark dark:outline dark:outline-2 dark:text-white inline-block font-medium" %>
  <%= link_to "Back to projects", projects_path, class: "ml-2 rounded-lg py-2 px-5 bg-gray-100 dark:bg-dark dark:outline dark:outline-2 dark:text-white inline-block font-medium" %>
</main>

app/views/projects/index.html+turbo_frame.erb
<%= turbo_frame_tag "page_handler" do %>
  <%= turbo_stream_action_tag("append", target: "projects", template: %(#{project_list_component projects: @projects})) %>
  <%= turbo_stream_action_tag("replace", target: "pager", template: %(#{render "pager", pagy: @pagy})) %>
<% end %>

app/views/projects/index.html.erb
<main class="flex-1">
  <%= page_header_component title: "Some projects I worked on", highlight: "Building awesome projects for awesome people" %>
  <% if user_signed_in? %>
    <div class="container mt-6 -mb-6">
      <%= button_component type: "create", link: new_project_path(@project), text: "Create new project", additionalClass: "mb-8" %>
    </div>
  <% end %>
  <%= turbo_frame_tag "page_handler" %>
  <div id="projects" class="container py-12 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-10">
    <%= project_list_component projects: @projects %>
  </div>
  <%= render "pager", pagy: @pagy %>
</main>

app/views/projects/new.html.erb
<main class="flex-1 container my-4">
  <h1 class="font-medium primary-text-color text-3xl">New project</h1>

  <%= render "form", project: @project %>

  <%= link_to 'Back to projects', projects_path, class: "ml-2 rounded-lg py-2 px-5 bg-gray-100 dark:bg-dark dark:outline dark:outline-2 dark:text-white inline-block font-medium" %>
</main>

app/views/projects/show.html.erb
<%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js", "data-turbo-track": "reload"  %>
<%= javascript_include_tag "quill", "data-turbo-track": "reload"  %>
<%= stylesheet_link_tag "monokai", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "quill/dist/quill.bubble.css", "data-turbo-track": "reload" %>

<main class="flex-1 container">
  <%= render @project %>
  <%if user_signed_in? %>
    <%= link_to 'Edit this project', edit_project_path(@project), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    <%= button_to 'Destroy this project', project_path(@project), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium mr-2" %>
  <%end%>
  <hr class="border-b dark:border-gray-700 transition-colors duration-200 my-5" />
  <%= link_to 'Go to projects page', projects_path, class: "text-main underline my-5" %>
</main>